version: '3.0'

services:
    nginx:
        build:
            context: ./docker/nginx
        volumes:
            - ./app:/symfony
        container_name: ${PROJECT_NAME}-nginx
        restart: always
        ports:
            - "8081:80"
        depends_on:
            - php

    php:
        build:
            context: ./docker/php
        volumes:
            - ./app:/symfony
        container_name: ${PROJECT_NAME}-php
        depends_on:
            - postgres

    postgres:
        build:
            context: ./docker/db
        volumes:
            - ./data/postgresql:/var/lib/postgresql/data
        container_name: ${PROJECT_NAME}-postgres
        restart: always
        ports:
            - "5432:5432"
        environment:
            - "POSTGRES_DB=${POSTGRES_DB}"
            - "POSTGRES_USER=${POSTGRES_USER}"
            - "POSTGRES_PASSWORD=${POSTGRES_PASSWORD}"

volumes:
    postgres:
